// Production ecosystem configuration
// Use this for production deployment (VM)

const path = require('path');
const { EnvironmentLoader } = require('../../packages/core-utils/dist/environment/EnvironmentLoader');

// Initialize environment loader
const envLoader = EnvironmentLoader.getInstance();
const env = envLoader.load();

// Generate consistent environment for all PM2 processes
const baseEnv = envLoader.generateEcosystemEnv();

const baseConfig = {
  env: baseEnv,
  env_production: {
    NODE_ENV: 'production',
    ...baseEnv,
  },
  max_memory_restart: '1G',
  restart_delay: 4000,
  time: true,
  merge_logs: false,
};

module.exports = {
  apps: [
    {
      name: 'api-gateway',
      script: path.join(__dirname, '../../apps/api-gateway/dist/server.js'),
      instances: 1,
      exec_mode: 'cluster',
      watch: false,
      ...baseConfig,
      error_file: path.join(__dirname, 'logs', 'api-gateway-error.log'),
      out_file: path.join(__dirname, 'logs', 'api-gateway-out.log'),
      log_file: path.join(__dirname, 'logs', 'api-gateway-combined.log'),
    },
    {
      name: 'ingestion-worker',
      script: path.join(__dirname, '../../workers/ingestion-worker/dist/index.js'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ...baseConfig,
      error_file: path.join(__dirname, 'logs', 'ingestion-worker-error.log'),
      out_file: path.join(__dirname, 'logs', 'ingestion-worker-out.log'),
      log_file: path.join(__dirname, 'logs', 'ingestion-worker-combined.log'),
    },
    {
      name: 'insight-worker',
      script: path.join(__dirname, '../../workers/insight-worker/dist/index.js'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ...baseConfig,
      error_file: path.join(__dirname, 'logs', 'insight-worker-error.log'),
      out_file: path.join(__dirname, 'logs', 'insight-worker-out.log'),
      log_file: path.join(__dirname, 'logs', 'insight-worker-combined.log'),
    },
    {
      name: 'ontology-optimization-worker',
      script: path.join(__dirname, '../../workers/ontology-optimization-worker/dist/index.js'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ...baseConfig,
      error_file: path.join(__dirname, 'logs', 'ontology-optimization-worker-error.log'),
      out_file: path.join(__dirname, 'logs', 'ontology-optimization-worker-out.log'),
      log_file: path.join(__dirname, 'logs', 'ontology-optimization-worker-combined.log'),
    },
    {
      name: 'card-worker',
      script: path.join(__dirname, '../../workers/card-worker/dist/index.js'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ...baseConfig,
      error_file: path.join(__dirname, 'logs', 'card-worker-error.log'),
      out_file: path.join(__dirname, 'logs', 'card-worker-out.log'),
      log_file: path.join(__dirname, 'logs', 'card-worker-combined.log'),
    },
    {
      name: 'embedding-worker',
      script: path.join(__dirname, '../../workers/embedding-worker/dist/index.js'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ...baseConfig,
      error_file: path.join(__dirname, 'logs', 'embedding-worker-error.log'),
      out_file: path.join(__dirname, 'logs', 'embedding-worker-out.log'),
      log_file: path.join(__dirname, 'logs', 'embedding-worker-combined.log'),
    },
    {
      name: 'graph-projection-worker',
      script: path.join(__dirname, '../../workers/graph-projection-worker/dist/index.js'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ...baseConfig,
      error_file: path.join(__dirname, 'logs', 'graph-projection-worker-error.log'),
      out_file: path.join(__dirname, 'logs', 'graph-projection-worker-out.log'),
      log_file: path.join(__dirname, 'logs', 'graph-projection-worker-combined.log'),
    },
    {
      name: 'conversation-timeout-worker',
      script: path.join(__dirname, '../../workers/conversation-timeout-worker/dist/index.js'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ...baseConfig,
      error_file: path.join(__dirname, 'logs', 'conversation-timeout-worker-error.log'),
      out_file: path.join(__dirname, 'logs', 'conversation-timeout-worker-out.log'),
      log_file: path.join(__dirname, 'logs', 'conversation-timeout-worker-combined.log'),
    },
    {
      name: 'maintenance-worker',
      script: path.join(__dirname, '../../workers/maintenance-worker/dist/index.js'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ...baseConfig,
      error_file: path.join(__dirname, 'logs', 'maintenance-worker-error.log'),
      out_file: path.join(__dirname, 'logs', 'maintenance-worker-out.log'),
      log_file: path.join(__dirname, 'logs', 'maintenance-worker-combined.log'),
    },
    {
      name: 'notification-worker',
      script: path.join(__dirname, '../../workers/notification-worker/dist/index.js'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ...baseConfig,
      error_file: path.join(__dirname, 'logs', 'notification-worker-error.log'),
      out_file: path.join(__dirname, 'logs', 'notification-worker-out.log'),
      log_file: path.join(__dirname, 'logs', 'notification-worker-combined.log'),
    },
    {
      name: 'spatial-query-worker',
      script: path.join(__dirname, '../../workers/spatial-query-worker/dist/index.js'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ...baseConfig,
      error_file: path.join(__dirname, 'logs', 'spatial-query-worker-error.log'),
      out_file: path.join(__dirname, 'logs', 'spatial-query-worker-out.log'),
      log_file: path.join(__dirname, 'logs', 'spatial-query-worker-combined.log'),
    },
    {
      name: 'video-generation-worker',
      script: path.join(__dirname, '../../workers/video-generation-worker/dist/index.js'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ...baseConfig,
      error_file: path.join(__dirname, 'logs', 'video-generation-worker-error.log'),
      out_file: path.join(__dirname, 'logs', 'video-generation-worker-out.log'),
      log_file: path.join(__dirname, 'logs', 'video-generation-worker-combined.log'),
    },
    {
      name: 'web-app',
      script: 'pnpm',
      args: 'start',
      cwd: path.join(__dirname, '../../apps/web-app'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ...baseConfig,
      env: {
        ...baseEnv,
        NEXT_PUBLIC_API_BASE_URL: 'http://34.136.210.47:3001',
        NEXT_PUBLIC_NOTIFICATION_SERVICE_URL: 'http://34.136.210.47:3002',
        NODE_ENV: 'production',
      },
      env_production: {
        NODE_ENV: 'production',
        ...baseEnv,
        NEXT_PUBLIC_API_BASE_URL: 'http://34.136.210.47:3001',
        NEXT_PUBLIC_NOTIFICATION_SERVICE_URL: 'http://34.136.210.47:3002',
      },
      error_file: path.join(__dirname, 'logs', 'web-app-error.log'),
      out_file: path.join(__dirname, 'logs', 'web-app-out.log'),
      log_file: path.join(__dirname, 'logs', 'web-app-combined.log'),
    },
  ],
};
